version: "2"
services:
  backend:
    image: groupiccn/students_manager:test
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      - local

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - local
  frontend:
    image: groupiccn/students_manager:test
    build: ./frontend
    links:
      - db
      - backend
    ports:
      - "3000:3000"
    networks:
      - local
networks:
  local:
    driver: bridge
